extraction:
  cpp:
    prepare:
      packages:
        - libconfig++-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libicu-dev
        - libturbojpeg0-dev
        - libpng-dev
        - libcurl4-openssl-dev
        - libjansson-dev
        - libssl-dev
        - libboost-system-dev
        - build-essential
        - cmake
        - pkg-config
        - libv4l-dev
        - libcamera-dev
        - libnetpbm10-dev
        - libexiv2-dev
        - libmysqlcppconn-dev
        - frei0r-plugins-dev
        - libpam0g-dev
        - libgstreamer1.0-dev
        - libgstreamer-plugins-base1.0-dev
        - libwebsocketpp-dev
        - libsdl2-dev
        - rygel
        - rygel-2.6-dev
        - libglib2.0-dev
        - libxml2-dev
        - libgee-0.8-dev
        - libgupnp-av-1.0-dev
        - libupnp-dev
        - libasound2-dev
        - libmagick++-dev
        - libavformat-dev
        - libswscale-dev
        - libavcodec-dev
        - libavutil-dev
        - libswresample-dev
        - libavresample-dev
        - libatomic1
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
